ISO_PERCENT_FIXED = 3.0

STRICT_PRECHECK_SAMPLES = 8
STRICT_ABS_EPS = 1e-10
STRICT_CANCEL_RATIO = 0.02
STRICT_MAX_CAP = 1e-6
VOLUME_ABS_EPS = 1e-10
ISO_ABS_EPS = 1e-12

EXTENT_TABLE_PATH = "extent_table.json"

DEFAULT_ORBITAL_ID = "1s(k=0)"
DEFAULT_MODE_LABEL = "切片（快速）"
DEFAULT_MODE_KEY = "slice"
DEFAULT_EXTENT_BASE = 6.0
DEFAULT_EXTENT_EFFECTIVE = 10.0
DEFAULT_RESOLUTION = 64
DEFAULT_INTEGRAL_SAMPLES = 32
DEFAULT_PREVIEW_QUALITY = "快速"
DEFAULT_FINAL_QUALITY = "高"

ALLOWED_RESOLUTIONS = (64, 96, 128, 160)

EMPTY_PROJECTION_MESSAGE = "无函数值，展示为空"
